### ISSUE TITLE
Uploading

### ISSUE THREAD

**Issue by dpsd16015** [merkourisa/Augmented-Reality#17]
Καλησπέρα, εφόσον έχουμε ολοκληρώσει απλά κάνουμε comit changes ολοκληρώνουμε το report και είναι ανεβασμένο;

**Comment by merkourisa** [comment]
@dpsd16015 αν υπάρχει κάποια απορία για κάποιο από τα παραδοτέα την κάνουμε στο αντίστοιχο issue και δεν ανοίγουμε νέο issue. Όσον αφορά το ερώτημα σου βλέπω ότι έχεις επεξεργαστεί το report σου
